version: "3"

services:
  redis:
    image: redis:6.2 
    container_name: redis
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    expose:
      - 6379
    networks:
      - app 
  db:
    image: postgres:13 
    container_name: db 
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - app 
    environment:
      - POSTGRES_DB=main
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pass
  celery:
    build:
      context: .
    container_name: celery
    command: pipenv run celery -A app worker -l info
    volumes:
      - ./:/opt/app:rw
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://admin:pass@db:5432/main
      - REDIS_URL=redis://redis:6379/
    networks:
      - app
  app:
    build:
      context: .
    container_name: app 
    expose:
      - 8000
    ports:
      - 8000:8000
    volumes:
      - ./:/opt/app:rw
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://admin:pass@db:5432/main
      - REDIS_URL=redis://redis:6379/
    networks:
      - app
networks:
  app:
    driver: bridge
