# Generated by Django 3.2 on 2021-04-29 09:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCallback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_secret', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('callback_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='customercallback',
            constraint=models.UniqueConstraint(condition=models.Q(deleted_at__isnull=True), fields=('callback_url',), name='udx_callback_url'),
        ),
    ]
