# Generated by Django 3.2 on 2021-04-29 10:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_key', models.TextField()),
                ('amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('account_number', models.TextField()),
                ('bank_code', models.TextField()),
                ('currency', models.TextField()),
                ('transaction_occured_at', models.DateTimeField(auto_now_add=True)),
                ('system_attempts', models.IntegerField(default=0)),
                ('user_attempts', models.IntegerField(default=0)),
                ('system_last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('user_last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('callback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.customercallback')),
            ],
        ),
        migrations.AddConstraint(
            model_name='customermessage',
            constraint=models.UniqueConstraint(condition=models.Q(deleted_at__isnull=True), fields=('external_key',), name='udx_external_key'),
        ),
    ]
